version: '3.7'

services:
  app:
    container_name: my_app_development_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=development
